### ISSUE TITLE
support descending for select queries

### ISSUE THREAD

**Issue by ender-wan** [shunfei/godruid#5]
Hi,

can you support descending for select queries, i think just need add this to QuerySelect struct, as [doc](http://druid.io/docs/0.10.1/querying/select-query.html), or i can submit a patch.

`
Descending  string                 `json:"descending"`
`

**Comment by QLeelulu** [comment]
We are not use druid anymore. So we don't maintain this project.

You can try https://github.com/TetrationAnalytics/godruid

**Comment by ender-wan** [comment]
thanks for your help!
